### ISSUE TITLE
Take the Router Challenge

### ISSUE THREAD

**Issue by grahammendick** [swan-io/chicane#17]
### Why it is needed?

[The Router Challenge](https://github.com/grahammendick/router-challenge) aims to be to Routers what TodoMVC was to MV* frameworks. It offers the same Music Catalog application built in React using different Routers. For it to be successful I need the help of Router writers like you. Will you [take the Router Challenge](https://github.com/grahammendick/router-challenge/blob/master/CONTRIBUTING.md) and implement the Music Catalog application using Chicane, please?

**Comment by zoontek** [comment]
Thanks, but we don't currently have the time for that 🙂
