### ISSUE TITLE
Unsafe ESLint errors

### ISSUE THREAD

**Issue by ahoyahoy** [swan-io/chicane#34]
### Bug summary

I am getting eslint errors

```
const Router = createRouter({
    Home: '/',
    About: '/about',
    UserList: '/users',
    UserDetail: '/users/:userId',
})


// Unsafe assignment of an `any` value @typescript-eslint/no-unsafe-assignment
// Unsafe call of an `any` typed  value @typescript-eslint/no-unsafe-call

```

### Library version

latest

### Environment info

```shell
nextjs page
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```ts
...
```

**Comment by zoontek** [comment]
@ahoyahoy You don't provide a lot of informations here, but I guess you just need to restart the `eslint` server here (Cmd + Shift + P in VScode):

<img width="630" alt="Screenshot 2023-01-24 at 12 20 45" src="https://user-images.githubusercontent.com/1902323/214279072-d9a288a9-bd46-4e54-87a5-61f51be1092a.png">

**Comment by ahoyahoy** [comment]
I'm sorry! Everything works perfectly now.
