### ISSUE TITLE
Default is not a func

### ISSUE THREAD

**Issue by bay-jacewhitten** [swan-io/chicane#39]
### Bug summary

    key: `${mumurhash(rawPath)}-${mumurhash(rawSearch + rawHash)}`,

so '/- ?page=users + no hash' 

causes this =>

location.ts:31 Uncaught TypeError: (0 , bt.default) is not a function
    at ha (location.ts:31:13)
    at history.ts:26:23

This is in a react app propject that is NOT using Typescript.

Thanks.

### Library version

latest

### Environment info

```shell
latest chrome, react 18
```

### Steps to reproduce

Using the lib

### Reproducible sample code

```ts
Proprietary
```

**Comment by zoontek** [comment]
Sorry, but I don't get your issue at all 😅
Could you be more specific? What does this means: `'/- ?page=users + no hash'`? You have a route which is `"/?:page"`?

Could you provide a small example to reproduce the issue?

**Comment by bay-jacewhitten** [comment]
I am using esBuild to bundle. This is a pure JS , react, jsx solution, so no TS at this time unfortunately.

**Comment by zoontek** [comment]
@bay-jacewhitten If you just want to try it, you can use vite, CRA or even CodeSandbox. The issue looks clearly like a bundler config issue (as the hash package if just a single file exposing a single, default exported function)
